{% set name = "spacy-alignments" %}
{% set module_name = "spacy_alignments" %}
{% set version = "0.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8dc358821591f576eef7bfe10187bc7b06b9a0c438a1f346170638718eff1263


build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
  host:
    - pip
    - python
    - setuptools
    - setuptools-rust
  run:
    - python

test:
  requires:
    - pytest
    - hypothesis
  imports:
    - {{ module_name }}
  commands:
    - python -m pytest --tb=native --pyargs {{ module_name }}

about:
  home: https://spacy.io/
  license: MIT
  license_file: LICENSE
  summary: Align tokenizations for spaCy + transformers
  description: |
    A spaCy package for Yohei Tamura's Rust tokenizations library.
  doc_url: https://github.com/explosion/spacy-alignments
  dev_url: https://github.com/explosion/spacy-alignments

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - adrianeboyd
